"use strict";

const NODE_NOT_EXISTS = 0;
const CLASS_NOT_DEFINED = 1;
const CONNECTION_TO_ITSELF = 2;
const IMPROPER_CONNECTION = 3;
const OBJECT_NOT_FOUND = 4;
const MANDATORY_PARAM = 5;
const INCORRECT_TYPE = 6;
const INCORRECT_PARENT_NODE = 7;

exports.NODE_NOT_EXISTS = NODE_NOT_EXISTS;
exports.CLASS_NOT_DEFINED = CLASS_NOT_DEFINED;
exports.CONNECTION_TO_ITSELF = CONNECTION_TO_ITSELF;
exports.IMPROPER_CONNECTION = IMPROPER_CONNECTION;
exports.OBJECT_NOT_FOUND = OBJECT_NOT_FOUND;
exports.MANDATORY_PARAM = MANDATORY_PARAM;
exports.INCORRECT_TYPE = INCORRECT_TYPE;
exports.INCORRECT_PARENT_NODE = INCORRECT_PARENT_NODE;
