"use strict";

const NODE_NOT_EXISTS = 0;
const CLASS_NOT_DEFINED = 1;
const CONNECTION_TO_ITSELF = 2;
const IMPROPER_CONNECTION = 3;
const OBJECT_NOT_FOUND = 4;

exports.NODE_NOT_EXISTS = NODE_NOT_EXISTS;
exports.CLASS_NOT_DEFINED = CLASS_NOT_DEFINED;
exports.CONNECTION_TO_ITSELF = CONNECTION_TO_ITSELF;
exports.IMPROPER_CONNECTION = IMPROPER_CONNECTION;
exports.OBJECT_NOT_FOUND = OBJECT_NOT_FOUND;
